badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  paper:
    envs:
    - host
    path: informe
    requirements: {}
    stages:
    - build
    vars: []
  powerset:
    envs:
    - host
    path: powerset
    requirements: {}
    stages:
    - setup
    - run
    vars: []
  squares:
    envs:
    - host
    path: squares
    requirements: {}
    stages:
    - setup
    - run
    vars: []
  stars:
    envs:
    - host
    path: stars
    requirements: {}
    stages:
    - generate-test-data
    - run-tests
    vars: []
popperized:
- github/popperized
